name: release

on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    env:
      INITIAL_VERSION: 11.0.0
      RELEASE_BRANCHES: main
      DEFAULT_BUMP: patch

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          WITH_V: true
          INITIAL_VERSION: ${{ env.INITIAL_VERSION }}
          RELEASE_BRANCHES: ${{ env.RELEASE_BRANCHES }}
          DEFAULT_BUMP: ${{ env.DEFAULT_BUMP }}